services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: snaplogic
      POSTGRES_PASSWORD: snaplogic
      POSTGRES_DB: snaplogic
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles: [ postgres-dev ]
    networks:
      - snaplogicnet

volumes:
  postgres_data:

networks:
  snaplogicnet:
    driver: bridge
