services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: snaplogic-activemq
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: false
      ARTEMIS_DEFAULT_ADDRESS_ROUTING_TYPE: BOTH
      ARTEMIS_DEFAULT_QUEUE_ROUTING_TYPE: ANYCAST
      ARTEMIS_AUTO_CREATE_QUEUES: true
      ARTEMIS_AUTO_CREATE_ADDRESSES: true
    volumes:
      # Mount ActiveMQ data to local directory
      - ../activemq-data:/var/lib/artemis-instance
      # Optional: Mount custom configuration
      # - ../config/broker.xml:/var/lib/artemis-instance/etc/broker.xml
    ports:
      - "8161:8161"  # Web Console
      - "61617:61616"  # JMS Port (changed to avoid conflicts)
      - "61614:61613"  # STOMP Port (changed to avoid conflicts)
      - "5673:5672"   # AMQP Port (changed to avoid conflicts)
    profiles: [ activemq , activemq-dev ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8161/console/ || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - snaplogicnet

  activemq-setup:
    image: curlimages/curl:latest
    container_name: snaplogic-activemq-setup
    depends_on:
      activemq:
        condition: service_healthy
    volumes:
      - ./scripts/activemq-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/sh", "/setup.sh"]
    profiles: [ activemq ]
    networks:
      - snaplogicnet

# Named volume no longer needed - using local bind mount instead
# volumes:
#   activemq_data:

networks:
  snaplogicnet:
    driver: bridge
