services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: Oracle123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ../oracle-init:/opt/oracle/scripts/startup
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus -s system/Oracle123@localhost/FREEPDB1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    profiles: [ dev, oracle-dev ]
    networks:
      - snaplogicnet

  oracle-schema-init:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite
    container_name: oracle-schema-init
    depends_on:
      oracle-db:
        condition: service_healthy
    command: |
      bash -c "
      echo 'Oracle is healthy, creating TEST schema...'
      sqlplus system/Oracle123@oracle-db:1521/FREEPDB1 <<'EOF'
      SET SERVEROUTPUT ON;
      BEGIN
          EXECUTE IMMEDIATE 'CREATE USER TEST IDENTIFIED BY Test123';
          DBMS_OUTPUT.PUT_LINE('TEST user created successfully');
      EXCEPTION
          WHEN OTHERS THEN
              IF SQLCODE = -1920 THEN
                  DBMS_OUTPUT.PUT_LINE('TEST user already exists');
              ELSE
                  RAISE;
              END IF;
      END;
      /
      GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO TEST;
      GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO TEST;
      GRANT CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO TEST;
      SELECT username, account_status FROM dba_users WHERE username = 'TEST';
      EXIT;
      EOF
      echo 'TEST schema setup completed!'
      "
    profiles: [ dev, oracle-dev ]
    networks:
      - snaplogicnet

volumes:
  oracle_data:

networks:
  snaplogicnet:
    driver: bridge
