services:
  minio:
    image: minio/minio:latest
    container_name: snaplogic-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    profiles: [ minio , minio-dev ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - snaplogicnet

  minio-setup:
    image: minio/mc:latest
    container_name: snaplogic-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./scripts/minio-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/sh", "/setup.sh"]
    profiles: [ minio ]
    networks:
      - snaplogicnet

volumes:
  minio_data:

networks:
  snaplogicnet:
    driver: bridge
