# docker-compose.yml
include:
  - docker-compose.oracle.yml
  - docker-compose.groundplex.yml
  - docker-compose.s3emulator.yml
  - docker-compose.postgres.yml
  # - docker-compose.activemq.yml
  - docker-compose.sqlserver.yml
  - docker-compose.mysql.yml
  # - docker-compose.teradata.yml  # Commented out - requires special access from Teradata

services:
  tools:
    build:
      context: ../src/tools
      dockerfile: ../../docker/robot.Dockerfile
    container_name: snaplogic-test-example-tools-container
    image: snaplogic-test-example:latest
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../test:/app/test
      - ../.env:/app/.env
      - ../setup_env.sh:/app/setup_env.sh
      - ../test/suite/test_data:/opt/snaplogic/test_data
      # Optional: Add mounts for common local directories (uncomment as needed)
      # - ~/Documents:/opt/host-documents:ro
      # - ~/Downloads:/opt/host-downloads:ro
      # - ~/Desktop:/opt/host-desktop:ro
    command: [ "sh", "-c", "echo 'Tools container started' && tail -f /dev/null" ]
    profiles: [ tools ]
    networks:
      - snaplogicnet

networks:
  snaplogicnet:
    driver: bridge
